### ISSUE TITLE
Onclick behavior on the Safari

### ISSUE THREAD

**Issue by cihanandac** [kitconcept/volto-slider-block#15]
The images in the slides can't be clicked (to open the image link) on Chrome and Firefox. But on Safari, it behaves differently. When it is clicked, it goes to the URL of the image.

**Comment by davisagli** [comment]
@cihanandac I can't reproduce this with the demo slider at https://volto.kitconcept.dev/blocks-examples/sliders-carousels

Please provide the steps to set up a slider that has this problem, or a demo page where it can be seen.

Also, what version of the package are you using?

**Comment by cihanandac** [comment]
I found the solution by customizing the 'DefaultBody.jsx'. Deleted href parameter from the 'MaybeWrap' component, and voila! Now it is just an image slider. Again, thank you for writing back.

**Comment by davisagli** [comment]
@cihanandac This slider is designed to always link to the item that is selected (i.e. it's more of a carousel for a landing page than an image gallery). So I think that customization is probably the way you have to go to avoid linking.
