### ISSUE TITLE
[object Object] for images component in Slider View

### ISSUE THREAD

**Issue by Fosten** [kitconcept/volto-slider-block#24]
After upgrading to Volto 17, I haven't had any luck with this slider.
I am currently running Volto 17.0.0-alpha.23 and volto-slider-block 4.3.0.

Getting [object Object] on images.

<img width="417" alt="Screen Shot 2023-08-09 at 1 30 34 PM" src="https://github.com/kitconcept/volto-slider-block/assets/1520484/26e70d03-5257-44bd-8435-819288b00ecd">

My best guess is that maybe need something like this which I believe fixed a similar issue for teasers?
https://github.com/plone/volto/commit/09e809f06951d301e7ca2b45e9129af550db282c

And may/may-not have been related to this discussion?
https://github.com/plone/volto/pull/3337
Note: It requires the latest version of `plone.restapi` (>=8.42.0) installed in the backend to work properly.
https://dist.plone.org/release/6.0.6/constraints.txt ... plone.restapi==8.40.0

However, since I am using 8.40.0 fine with Teasers I'm guessing it's more closely related to the first commit?
Thank you for any advice.

**Comment by davisagli** [comment]
@Fosten This addon needs some updates to work with the updated image rendering in volto. Until that happens, it doesn't support Volto releases greater than 17.0.0-alpha.20

**Comment by fredvd** [comment]
Finding this issue by chance. I think it can be closed,  the README suggests to user version 5 or higher of this add'on with Volto 17: 

Version | Volto version
-- | --
>=5.0.0 | >=17.0.0-alpha.27
>=3.0.0 | >=16.0.0-rc.2
<=2.1.0 | <=16.0.0-a50

@Fosten if this is incorrect, please re-open
